### ISSUE TITLE
fetch olarak

### ISSUE THREAD

**Issue by erennyuksell** [bkadilar/php-gib-vkn-vd-api#1]
Merhaba bir javascript projesi üzerinde çalışmaktayım.  Vergi numarası ile doğrulama yapmam gerekiyor. PHP olarak maalesef işime yaramıyor. Kodu token alan ve vergi dairesi sorgulayan şekilde JS fetch olarak paylaşma şansınız var mı?

**Comment by bkadilar** [comment]
> Merhaba bir javascript projesi üzerinde çalışmaktayım. Vergi numarası ile doğrulama yapmam gerekiyor. PHP olarak maalesef işime yaramıyor. Kodu token alan ve vergi dairesi sorgulayan şekilde JS fetch olarak paylaşma şansınız var mı?

postman den kodu olduğu gibi çevirebilirsiniz istediğiniz dil için

**Comment by Serkan-Iskender** [comment]
Postman collection 2.1 dosyası içeriği json uzantılı kaydedip postmanda açabilirsiniz. @erennyuksell 
`{
	"info": {
		"_postman_id": "ff5a5e9f-8027-480b-995f-3715e881476c",
		"name": "GIB Sorgu",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "6940427"
	},
	"item": [
		{
			"name": "token",
			"request": {
				"method": "POST",
				"header": [
					{
						"key": "Content-Type",
						"value": "application/x-www-form-urlencoded",
						"type": "text"
					},
					{
						"key": "content",
						"value": "assoscmd=cfsession&rtype=json&fskey=intvrg.fix.session&fuserid=INTVRG_FIX",
						"type": "text"
					}
				],
				"body": {
					"mode": "urlencoded",
					"urlencoded": [
						{
							"key": "assoscmd",
							"value": "cfsession",
							"type": "text"
						},
						{
							"key": "rtype",
							"value": "json",
							"type": "text"
						},
						{
							"key": "fskey",
							"value": "intvrg.fix.session",
							"type": "text"
						},
						{
							"key": "fuserid",
							"value": "INTVRG_FIX",
							"type": "text"
						}
					]
				},
				"url": {
					"raw": "https://ivd.gib.gov.tr/tvd_server/assos-login",
					"protocol": "https",
					"host": [
						"ivd",
						"gib",
						"gov",
						"tr"
					],
					"path": [
						"tvd_server",
						"assos-login"
					],
					"query": [
						{
							"key": "assoscmd",
							"value": "cfsession",
							"disabled": true
						},
						{
							"key": "rtype",
							"value": "json",
							"disabled": true
						},
						{
							"key": "fskey",
							"value": "intvrg.fix.session",
							"disabled": true
						},
						{
							"key": "fuserid",
							"value": "INTVRG_FIX",
							"disabled": true
						}
					]
				}
			},
			"response": []
		},
		{
			"name": "vkn sorgu",
			"request": {
				"method": "POST",
				"header": [
					{
						"warning": "This is a duplicate header and will be overridden by the Content-Type header generated by Postman.",
						"key": "Content-Type",
						"value": "application/x-www-form-urlencoded",
						"type": "text"
					}
				],
				"body": {
					"mode": "urlencoded",
					"urlencoded": [
						{
							"key": "cmd",
							"value": "vergiNoIslemleri_vergiNumarasiSorgulama",
							"type": "text"
						},
						{
							"key": "callid",
							"value": "ff81dd010b12d-8",
							"type": "text"
						},
						{
							"key": "pageName",
							"value": "R_INTVRG_INTVD_VERGINO_DOGRULAMA",
							"type": "text"
						},
						{
							"key": "token",
							"value": "d1078f5e3dc646b78d5d4e5842f21e97feb48d366bc7617458b6679dec12675154a01fccc42292bb04d926bc259dbc75e39dd8e202535fd70a7098396c74a6f7",
							"type": "text"
						},
						{
							"key": "jp",
							"value": "{\"dogrulama\":{\"vkn1\":\"3810071289\",\"tckn1\":\"\",\"iller\":\"6\",\"vergidaireleri\":\"006283\"}}",
							"type": "text"
						}
					]
				},
				"url": {
					"raw": "https://ivd.gib.gov.tr/tvd_server/dispatch",
					"protocol": "https",
					"host": [
						"ivd",
						"gib",
						"gov",
						"tr"
					],
					"path": [
						"tvd_server",
						"dispatch"
					]
				}
			},
			"response": []
		}
	]
}`

**Comment by erennyuksell** [comment]
Teşekkür ederim uzun zaman önce halletmiştim zaten. Bu arada vergi daireleri güncellendi aklınızda bulunsun.
